## Cubic Spline Interpolation

In [6]:
import numpy as np 
import matplotlib.pyplot as plt

In [7]:
x = np.array([1,2,4,6,9])
y = np.array([15, 14, 10,14,16])
n = len(x) -1

h = np.diff(x)
h

array([1, 2, 2, 3])

In [8]:
Dy = np.diff(y)
Dy

array([-1, -4,  4,  2])

In [9]:
A = np.zeros((n-1, n+1))
A

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [13]:
for i in range(n-1):
    A[i,i] = h[i]
    A[i, i+1] = 2*(h[i]+h[i+1])
    A[i, i+2] = h[i+1]
A

array([[ 1.,  6.,  2.,  0.,  0.],
       [ 0.,  2.,  8.,  2.,  0.],
       [ 0.,  0.,  2., 10.,  3.]])

In [14]:
B = np.zeros(n-1)
B

array([0., 0., 0.])

In [16]:
for i in range(n-1):
    B[i] = 6 * (Dy[i+1]/h[i+1] - Dy[i]/h[i])
    
B

array([-6., 24., -8.])

In [20]:
M = np.linalg.solve(A, B)

LinAlgError: Last 2 dimensions of the array must be square